version: '3.8'

services:

  sqlsrv:
    container_name: app-mssql-local
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "Aerlon063"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_COLLATION: "LATIN1_GENERAL_100_CI_AS_SC_UTF8"
    volumes:
      - './volumes/:/var/opt/mssql/data'
    user: root


  php:
    container_name: app-php
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    volumes:
      - '.:/var/www/html'
      - './Docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro'
      - './Docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro'
    environment:
      - ACCEPT_EULA=Y
      - COMPOSER_ALLOW_SUPERUSER=1
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=remote_host=host.docker.internal remote_port=9003 idekey=VSCODE
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
      # "depends_on ->so vai subir o container do php depois que o banco de dados subir 
    depends_on:
      - sqlsrv

  node:
    container_name: app-node
    build:
      context: .
      dockerfile: ./Docker/node/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    ports:
      - "5173:5173"
    volumes:
      - '.:/var/www/html'
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - php
    networks:
      - app-network
  

  nginx:
    container_name: app-nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - '.:/var/www/html'
      - './Docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - php
    networks:
      - app-network    
  
networks:
  app-network:
    driver: bridge


#so terá acesso a internet se tiver o "drive: bridge". se nao colocar bridge nao vai funcionar;